services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:16
    networks:
      - internal
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data

  temporal:
    container_name: temporal
    depends_on:
      - postgres
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
      - POSTGRES_SEEDS=postgres
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/dynamic-config/development.yaml
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
      - PROMETHEUS_ENDPOINT=temporal:7299

    image: temporalio/auto-setup:1.28.1
    networks:
      - internal
    ports:
      - 7233:7233
      - 7299:7299
    volumes:
      - ./temporal:/etc/temporal/dynamic-config

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:1.28.1-tctl-1.18.4-cli-1.4.1
    networks:
      - internal
    stdin_open: true
    tty: true

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:2.34.0
    networks:
      - internal
    ports:
      - 8080:8080

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    restart: always
    networks:
      - default

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    restart: always
    networks:
      - default

  account:
    container_name: account
    environment:
      - DB_URI=postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - TEMPORAL_HOST=temporal:7233
    ports:
      - 8001:8080
    networks:
      - internal
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: account
    restart: always
    depends_on:
      - postgres
      - temporal

  fraud:
    container_name: fraud
    environment:
      - TEMPORAL_HOST=temporal:7233
    ports:
      - 8002:8080
    networks:
      - internal
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: fraud
    restart: always
    depends_on:
      - postgres
      - temporal

  notification:
    container_name: notification
    environment:
      - TEMPORAL_HOST=temporal:7233
    ports:
      - 8003:8080
    networks:
      - internal
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: notification
    restart: always
    depends_on:
      - postgres

  payment:
    container_name: payment
    environment:
      - TEMPORAL_HOST=temporal:7233
    ports:
      - 8004:8080
    networks:
      - internal
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: payment
    restart: always
    depends_on:
      - postgres
      - temporal

  # reporting:
  #   ports:
  #     - 8005:8080
  #   networks:
  #     - internal
  #   build:
  #     context: ./reporting
  #     dockerfile: ../Dockerfile
  #   depends_on:
  #     - postgres

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  internal:
    driver: bridge